spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/AIC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ko951124!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 477513164463-2sim4u0eddbevbqat27c7l58euqp6t7i.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: h010kVzKZdy3KySdqbZT
            client-secret: tB8R5ngy1g
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - name
              - email
          kakao:
            client-id: 9f0db17e2c7784e11667950fdf23fd57
            client-secret: 3VP5prSwQ7ZLS2oYwsLHMoKg7eqLGoeX
            client-name: Kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8080


